[build]
builder = "nixpacks"
buildCommand = "yarn install --frozen-lockfile"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
