services:
  - type: web
    name: pmserver-api
    env: node
    plan: free
    buildCommand: yarn install --frozen-lockfile
    startCommand: yarn start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
